stages:
  - build
  - test
  - image_build

build:
  stage: build
  image: gradle:jdk14
  script:
    - ls
    - chmod +x ./gradlew
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master

test:
  stage: test
  image: gradle:jdk14
  script:
    - chmod +x ./gradlew
    - ./gradlew test
  only:
    - master

image_build:
  stage: image_build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - master



